# Generated by Django 5.2.5 on 2025-10-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusanga', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
