# Generated by Django 5.2.5 on 2025-10-04 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusanga', '0005_alter_module_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('scorm', 'SCORM'), ('xapi', 'xAPI'), ('text', 'Text')], default='video', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='modules/files/'),
        ),
        migrations.AddField(
            model_name='module',
            name='scorm_package',
            field=models.FileField(blank=True, null=True, upload_to='modules/scorm/'),
        ),
        migrations.AddField(
            model_name='module',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=50)),
                ('score', models.FloatField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progress', to='kusanga.enrollment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kusanga.module')),
            ],
            options={
                'unique_together': {('enrollment', 'module')},
            },
        ),
    ]
