# Generated by Django 5.2.5 on 2025-10-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusanga', '0006_enrollment_completed_module_content_type_module_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='scorm_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
