# Generated by Django 5.2.5 on 2025-10-05 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kusanga', '0007_module_scorm_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='scorm_path',
        ),
    ]
