# Generated by Django 5.2.5 on 2026-01-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusanga', '0008_remove_module_scorm_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('trainer', 'Trainer'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
