# Generated by Django 5.2.5 on 2026-01-23 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusanga', '0009_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('competent', 'Competent'), ('not_competent', 'Not Competent')], max_length=50)),
                ('achieved_on', models.DateTimeField(blank=True, null=True)),
                ('expires_on', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_record', to='kusanga.enrollment')),
            ],
        ),
        migrations.DeleteModel(
            name='ComplianceRecord',
        ),
    ]
