# Generated by Django 5.2.5 on 2026-03-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusanga', '0011_coursegroup_usercoursegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='record_type',
            field=models.CharField(choices=[('compliance', 'Compliance'), ('competence', 'Competence')], default='compliance', max_length=20),
        ),
    ]
