# Generated by Django 5.2.5 on 2026-08-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusanga', '0012_course_record_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scormtracking',
            name='lesson_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
