# Generated by Django 5.2.5 on 2026-08-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusanga', '0013_scormtracking_lesson_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_started', max_length=50),
        ),
    ]
