# Generated by Django 5.2.5 on 2026-08-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusanga', '0014_alter_moduleprogress_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('scorm', 'SCORM'), ('xapi', 'xAPI'), ('video', 'Video'), ('pdf', 'PDF')], max_length=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('scorm', 'SCORM'), ('xapi', 'xAPI')], default='video', max_length=20),
        ),
    ]
