# Generated by Django 5.2.5 on 2026-08-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kusanga', '0015_alter_course_course_type_alter_module_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='expiry_months',
            field=models.PositiveIntegerField(blank=True, help_text='Number of months a completed course remains valid', null=True),
        ),
    ]
